"""Trackers table

Revision ID: 933dc6125cf7
Revises: 
Create Date: 2018-01-09 11:31:54.266271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '933dc6125cf7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=24), nullable=True),
    sa.Column('vendor', sa.String(length=64), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracker_phone_number'), 'tracker', ['phone_number'], unique=False)
    op.create_index(op.f('ix_tracker_timestamp'), 'tracker', ['timestamp'], unique=False)
    op.create_index(op.f('ix_tracker_vendor'), 'tracker', ['vendor'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tracker_vendor'), table_name='tracker')
    op.drop_index(op.f('ix_tracker_timestamp'), table_name='tracker')
    op.drop_index(op.f('ix_tracker_phone_number'), table_name='tracker')
    op.drop_table('tracker')
    # ### end Alembic commands ###
